name: Sample Request
description: There is something that you don't find clear to implement with Shiny and it does not exist in these samples
title: "[Sample Request]: "
body:
  - type: markdown
    attributes:
      value: |
        Please do not request things like "How do I connect to this device with BLE?" or Samples that don't have anything to do with the existing feature set offered with Shiny
  - type: textarea
    attributes:
      label: Summary of Sample you would like to see
    validations:
      required: true
